## This is basic continuous integration build for your Quarkus application.
name: Quarkus build CI

on:
  push:
  # Run on every branch push: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    # Code Build steps
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      # Checkout maven lifecycles: https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
      - name: Build with Maven
        run: mvn verify -B